version: '2'
services:
  app:
    build: .
    ports:
      - 3000:8080
    links:
      - mongo
    restart: always

  nginx_static:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/word-assistant/html:/usr/share/nginx/html
      - /data/word-assistant/nginx/conf.d:/etc/nginx/conf.d
      - /data/word-assistant/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/ssl:/root/ssl

  nginx_node:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /data/word-assistant/nginx_node/conf.d:/etc/nginx/conf.d
      - /data/word-assistant/nginx_node/nginx.conf:/etc/nginx/nginx.conf
      - /root/ssl:/root/ssl
    volumes_from:
      - app
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - /data/word-assistant/db:/data/db
