version: '2'
services:
  app:
    build: .
    ports:
      - 8080:3001
    links:
      - mongo
    volumes:
      - /data/word-assistant:/usr/src/app/public
    restart: always
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
